global:
  image: {}
  rollingUpdate: {}

# -- (bool) Start Fastify app in debug mode with nodejs inspector
# inspector port is 9320
debug: false

# -- (string) The log level of the application.
# one of 'fatal', 'error', 'warn', 'info', 'debug', 'trace'; 
# also 'silent' is supported to disable logging. 
# Any other value defines a custom level and requires supplying a level value via levelVal. 
# @default -- `info`.
logLevel: "info"

# -- (int) The maximum amount of time in milliseconds in which a fastify plugin can load. 
# If not, ready will complete with an Error with code 'ERR_AVVIO_PLUGIN_TIMEOUT'.
# @default -- Default to 10000 (10 seconds).
pluginTimeout: 

# -- (int) Defines the maximum payload, in bytes, that the server is allowed to accept
# @default -- Default to 10485760 (10MB).
bodyLimit: 10485760

# -- (int) The maximum amount of time before forcefully closing pending requests.
# This should set to a value lower than the Pod's termination grace period (which is default to 30s)
# @default -- Default to 25000 (25s).
closeGraceDelay: 25000

# image setting loadding order: (from higher priority to lower priority)
# - Values.image.x
# - Values.defaultImage.x
# You can set `imagePullSecret` value to `false` (bool) to reset the value (see example below)

image: 
  name: "magda-embedding-api"
  # repository: 
  # pullPolicy: 
  # imagePullSecret: 

defaultImage:
  repository: ghcr.io/magda-io
  pullPolicy: IfNotPresent
  imagePullSecret: false

nameOverride: ""
fullnameOverride: ""

replicas: 1

autoscaling:
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 90
    targetMemory: ""  

priorityClassName: magda-9

podSecurityContext:
  runAsUser: 1000

rbac:
  create: false
  serviceAccountAnnotations: {}
  serviceAccountName: ""
  # -- Controls whether or not the Service Account token is automatically mounted to /var/run/secrets/kubernetes.io/serviceaccount
  automountServiceAccountToken: false

hostAliases: []

startupProbe:
  httpGet:
    path: /status/startup
    port: 3000
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30
  successThreshold: 1
  initialDelaySeconds: 10

livenessProbe:
  httpGet:
    path: /status/liveness
    port: 3000
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1
  initialDelaySeconds: 10

readinessProbe:
  httpGet:
    path: /status/readiness
    port: 3000
  periodSeconds: 20
  timeoutSeconds: 5
  failureThreshold: 10
  successThreshold: 1
  initialDelaySeconds: 10

extraEnvs: []
#  - name: "NODE_OPTIONS"
#    value: "--max-old-space-size=1800"

envFrom: []

extraVolumes: []
  # - name: extras
  #   emptyDir: {}

extraVolumeMounts: []
  # - name: extras
  #   mountPath: /usr/share/extras
  #   readOnly: true

extraInitContainers: ""

extraContainers: ""

service:
  name: "magda-embedding-api"
  type: ClusterIP
  # The IP family and IP families options are to set the behaviour in a dual-stack environment
  # Omitting these values will let the service fall back to whatever the CNI dictates the defaults
  # should be
  #
  # ipFamilyPolicy: SingleStack
  # ipFamilies:
  # - IPv4
  port: 80
  targetPort: 3000
  loadBalancerIP: ""
  nodePort: ""
  labels: {}
  annotations: {}
  loadBalancerSourceRanges: []
  # 0.0.0.0/0
  httpPortName: http

nodeSelector: {}

tolerations: []

affinity: {}

# -- This is the pod topology spread constraints
# https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
topologySpreadConstraints: []

# -- pod lifecycle policies as outlined here:
# https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks
lifecycle: {}

deploymentAnnotations: {}
podAnnotations: {}

resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    memory: "512M"