apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ template "magda.fullname" . }}-appconfig"
  labels:
    {{- include "magda.common.labels.standard" . | nindent 4 }}
data:
  appConfig.json: {{ .Values.appConfig | mustToRawJson | quote }}