apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "magda.fullname" . | quote }}
  labels: 
    {{- include "magda.common.labels.standard" . | nindent 4 -}}
  {{- with .Values.dashboardAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if not .Values.autoscaling.hpa.enabled }}
  replicas: {{ .Values.replicas | default 1 }}
{{- end }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      {{- include "magda.common.labels.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "magda.common.labels.standard" . | nindent 8 }}
      {{- if or (empty .Values.podAnnotations | not) (empty .Values.config | not) }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- /* This forces a restart if the configmap has changed */}}
        appconfigchecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
      {{- end }}
    spec:
{{- if and .Values.priorityClassName .Values.global.enablePriorityClass }}
      priorityClassName: {{ .Values.priorityClassName }}
{{- end }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      {{- if and .Values.rbac.create (eq .Values.rbac.serviceAccountName "") }}
      serviceAccountName: {{ include "magda.fullname" . | quote }}
      automountServiceAccountToken: {{ ne .Values.rbac.automountServiceAccountToken false }}
      {{- else if and .Values.rbac.create (ne .Values.rbac.serviceAccountName "") }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName | quote }}
      automountServiceAccountToken: {{ ne .Values.rbac.automountServiceAccountToken false }}
      {{- else }}
      automountServiceAccountToken: {{ ne .Values.rbac.automountServiceAccountToken false }}
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases: {{ toYaml .Values.hostAliases | nindent 6 }}
      {{- end }}
      volumes:
        - name: appConfig
          configMap:
            name: "{{ template "magda.fullname" . }}-appConfig"
            items:
            - key: appConfig.json
              path: appConfig.json
        {{- if .Values.extraVolumes }}
        # Currently some extra blocks accept strings
        # to continue with backwards compatibility this is being kept
        # whilst also allowing for yaml to be specified too.
        {{- if eq "string" (printf "%T" .Values.extraVolumes) }}
{{ tpl .Values.extraVolumes . | indent 8 }}
        {{- else }}
{{ toYaml .Values.extraVolumes | indent 8 }}
        {{- end }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
{{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
    {{- end }}
      {{- include "magda.imagePullSecrets" . | indent 6 }}
      {{- if .Values.extraInitContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      initContainers:
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 6 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 6 }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name | quote }}
        securityContext:
{{ toYaml .Values.securityContext | indent 10 }}
        image: {{ include "magda.image" . | quote }}
        imagePullPolicy: {{ include "magda.imagePullPolicy" . | quote }}
        command:
        - "node"
        - "./node_modules/fastify-cli/cli.js"
        - "start"
        - "dist/app.js"
        {{- if .Values.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.Version }}
        {{- if .Values.readinessProbe }}
        startupProbe:
{{ toYaml .Values.startupProbe | indent 10 }}
        {{- end }}
        {{- end }}
        env:
        - name: FASTIFY_PORT
          value: {{ .Values.service.targetPort | quote }}
        {{- if .Values.debug }}
        - name: FASTIFY_DEBUG
          value: "true"
        {{- end }}
        {{- if .Values.pluginTimeout }}
        - name: FASTIFY_PLUGIN_TIMEOUT
          value: {{ .Values.pluginTimeout | int | quote }}
        {{- end }}
        - name: FASTIFY_LOG_LEVEL
          value: {{ .Values.logLevel | quote }}
        - name: FASTIFY_BODY_LIMIT
          value: {{ .Values.bodyLimit | int | quote }}
        - name: FASTIFY_CLOSE_GRACE_DELAY
          value: {{ .Values.closeGraceDelay | int | quote }}
{{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | indent 8 }}
{{- end }}
{{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | indent 10 }}
{{- end }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: {{ .Values.service.httpPortName | default "http" }}
          protocol: TCP
{{- if .Values.lifecycle }}
        lifecycle:
{{ toYaml .Values.lifecycle | indent 10 }}
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - name: appConfig
            mountPath: /etc/config/appConfig.json
            subPath: appConfig.json
          {{- if .Values.extraVolumeMounts }}
          # Currently some extra blocks accept strings
          # to continue with backwards compatibility this is being kept
          # whilst also allowing for yaml to be specified too.
          {{- if eq "string" (printf "%T" .Values.extraVolumeMounts) }}
{{ tpl .Values.extraVolumeMounts . | indent 10 }}
         {{- else }}
{{ toYaml .Values.extraVolumeMounts | indent 10 }}
          {{- end }}
          {{- end }}
      {{- if .Values.extraContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .Values.extraContainers) }}
{{ tpl .Values.extraContainers . | indent 6 }}
      {{- else }}
{{ toYaml .Values.extraContainers | indent 6 }}
      {{- end }}
      {{- end }}