image:
  # you can use minikube Registry Aliases Addon to setup the registry alias example.com in local test cluster
  # https://minikube.sigs.k8s.io/docs/handbook/addons/registry-aliases/
  repository: example.com
  tag: latest
  pullPolicy: Always
# extends plugin timeout to 60 seconds so the model can be downloaded
pluginTimeout: 1200000
startupProbe:
  failureThreshold: 30
resources:
  requests:
    memory: "350M"
  limits:
    memory: "400M"
appConfig:
  modelList:
  # use alternative model for embedding
  - name: Xenova/bge-small-en-v1.5
    # set quantized to false to use the non-quantized version of the model
    # by default, the quantized version of the model will be used
    quantized: true
    extraction_config:
      pooling: "mean"
      normalize: true